### ISSUE TITLE
The window exceeds the taskbar.

### ISSUE THREAD

**Issue by Moussa-Ball** [dfct/TrueFramelessWindow#7]
**# By compiling the code, I notice that the window exceeds the taskbar.**

![sans titre](https://user-images.githubusercontent.com/17275595/28238974-ab778308-694f-11e7-8f49-ed840e49eee0.png)

**Comment by dfct** [comment]
Thanks Moussa! Q, if you go into Settings -> System -> Display, what is Scale: Change the Size of text, apps and other items set to on your machine?

**Comment by Moussa-Ball** [comment]
I have the same situation.

**Comment by dfct** [comment]
What % is the scale set to? 100%? 200%?

**Comment by Moussa-Ball** [comment]
100%

**Comment by dfct** [comment]
Perfect, okay; I'll spin up a Windows box at 100% later today and see if I see what you see.

**Comment by Moussa-Ball** [comment]
https://github.com/deimos1877/BorderlessWindow

**Comment by dfct** [comment]
This appears to be tied to a new Windows 10 change where they muck with borders (again) (even when you claim ownership of the frame). I'm not sure why it doesn't happen at 200% DPI, but does at 100%. 

I haven't found a fix yet. I've been trying the things mentioned in these SO posts as well as elsewhere, but no luck so far:
- https://stackoverflow.com/a/34143777
- https://stackoverflow.com/a/39735058

If anyone has found a workaround for this Win10, please do let me know..

**Comment by Moussa-Ball** [comment]
I solved the problem at home, it was the geometry and I no longer see the bugs when compiling, but I can not interact with the widgets that I put on the window. Someone could show me an example.

```
if (wp.showCmd == SW_MAXIMIZE)
{
     //Maximized window draw 8 pixels off screen
     childWidget->setGeometry(0, 0
     , winrect.right
     , winrect.bottom);
 }
else
{
    childWidget->setGeometry(0, 0 
    , winrect.right / childWidget->window()->devicePixelRatio()
    , winrect.bottom / childWidget->window()->devicePixelRatio());
}
```

**Comment by brumenn** [comment]
Hello,
For me the problem is still here when the window is maximized with areo snap.

**Comment by Moussa-Ball** [comment]
Look at the borderless window I made. I think you'll be comfortable with it.

https://github.com/Moussa-Ball/BorderlessWindowQt-Modern-Gui
